spring:
  mail:
    host: # 邮箱服务器 例：smtp.qq.com
    username: ****@qq.com
    password: ****
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true