spring:
  mail:
    host: smtp.qq.com
    username: 2659445660@qq.com
    password: iavgfyjhjcnrdice
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
