spring:
  mail:
    host: smtp.qq.com  # 邮箱服务器
    username: 2659445660@qq.com
    password: trbbqwlysfncdihd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
